import initAccordian from "./modules/accordion.js";
import initDropDownMenu from "./modules/dropdown-menu.js";
import initModal from "./modules/modal.js";
import initAnimacaoScroll from "./modules/scroll-animacao.js";
import initScrollSuave from "./modules/scroll-suave.js";
import initTabNav from "./modules/tabnav.js";
import initTooltip from "./modules/tooltip.js";
import initMenuMobile from "./modules/menu-mobile.js";
import initFuncionamento from "./modules/funcionamento.js";
import InitFetchAnimais from "./modules/fetch-animais.js";
import initFetchBitcoin from "./modules/fetch-bitcoin.js";

initAccordian();
initDropDownMenu();
initModal();
initAnimacaoScroll();
initScrollSuave();
initTabNav();
initTooltip();
initMenuMobile();
initFuncionamento();
InitFetchAnimais();
initFetchBitcoin();
